name: Build report

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex

    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        run: pandoc informe.md -o informe.pdf

      - name: Build HTML
        run: pandoc informe.md -s --mathjax -o informe.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: informe
          path: |
            informe.pdf
            informe.html
